jwt:
  secretKey:${JWT_SECRET_KEY}

spring:
  application:
    name: api-gateway

#api gateway config
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - StripPrefix=2
            - name: LoggingOrdersFilter
            - name: Authentication
              args:
                isEnabled: true
#            - name: Authorization
#              args:
#                allowedRoles: ADMIN, SUPER_ADMIN

        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/v1/inventory/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=X-Custom-Header, Krishnakant
            - name: Authentication

#eureka configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
