management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

resilience4j:
  retry:
    configs:
      default:
        maxRetryAttempts: 3
        waitDuration: 5s
    instances:
      inventoryRetry:
        baseConfig: default
        waitDuration: 5s         # we can overwrite the value
  ratelimiter:
    instances:
      inventoryRateLimiter:
        limitRefreshPeriod: 5s   # 1 request allowed every 5 seconds
        limitForPeriod: 1
        timeoutDuration: 1s      # wait max 1s, then fail

  circuitbreaker:
    instances:
      inventoryCircuitBreaker:
        registerHealthIndicator: true        # Exposes circuit breaker health via Actuator
        slidingWindowSize: 10                # Number of recent calls used to calculate failure rate
        slidingWindowType: COUNT_BASED       # Uses number of calls (not time) for the sliding window
        minimumNumberOfCalls: 10             # Minimum number of calls before calculating the failure rate
        failureRateThreshold: 50             # Opens circuit if 50% or more calls fail
        waitDurationInOpenState: 20s         # Time circuit stays OPEN before moving to HALF_OPEN
        permittedNumberOfCallsInHalfOpenState: 3 # Number of test calls in HALF_OPEN state
        eventConsumerBufferSize: 10          # Number of circuit breaker events stored for monitoring

#These configuration are not suitable for the production